config/routes.rb
Rails.application.routes.draw do
  resources :invstatuses
  resources :product_orders
  resources :service_orders
  resources :notes
  resources :invoices
  resources :transportations
  resources :chemicals
  resources :suppliers
  resources :supplierpaymentinfos
  resources :supporting_companies
  resources :scpaymentinfos
  resources :stlservices
  resources :servstatuses
  resources :servcategories
  resources :stlclients
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :products
  resources :prodstatuses
  resources :prodcategories
  resources :employees
  resources :home
  devise_for :users

  root to: "home#index"

  get 'home', to: 'home#index'
  get 'report', to: 'reports#show'
  get 'transportation', to: 'transportations#index'
  get 'product', to: 'products#index'
  get 'chemical', to: 'chemicals#index'
  get 'employee', to: 'employees#index'
  get 'stlclient', to: 'stlclients#index'
  get 'supporting', to: 'supporting_companies#index'
  get 'supplier', to: 'suppliers#index'
  get 'invoice', to: 'invoices#index'
  
end

app/models/servcategory.rb
class Servcategory < ApplicationRecord
    has_many :stlservices
end

app/controllers/servcategories_controller.rb
class ServcategoriesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_servcategory, only: [:show, :edit, :update, :destroy]

  # GET /servcategories
  # GET /servcategories.json
  def index
    @servcategories = Servcategory.all
  end

  # GET /servcategories/1
  # GET /servcategories/1.json
  def show
  end

  # GET /servcategories/new
  def new
    @servcategory = Servcategory.new
  end

  # GET /servcategories/1/edit
  def edit
  end

  # POST /servcategories
  # POST /servcategories.json
  def create
    @servcategory = Servcategory.new(servcategory_params)

    respond_to do |format|
      if @servcategory.save
        format.html { redirect_to @servcategory, notice: 'Servcategory was successfully created.' }
        format.json { render :show, status: :created, location: @servcategory }
      else
        format.html { render :new }
        format.json { render json: @servcategory.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /servcategories/1
  # PATCH/PUT /servcategories/1.json
  def update
    respond_to do |format|
      if @servcategory.update(servcategory_params)
        format.html { redirect_to @servcategory, notice: 'Servcategory was successfully updated.' }
        format.json { render :show, status: :ok, location: @servcategory }
      else
        format.html { render :edit }
        format.json { render json: @servcategory.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /servcategories/1
  # DELETE /servcategories/1.json
  def destroy
    @servcategory.destroy
    respond_to do |format|
      format.html { redirect_to servcategories_url, notice: 'Servcategory was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_servcategory
      @servcategory = Servcategory.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def servcategory_params
      params.require(:servcategory).permit(:category)
    end
end

app/helpers/servcategories_helper.rb
module ServcategoriesHelper
end

app/views/servcategories/_form.html.erb
<%= form_with(model: servcategory, local: true) do |form| %>
  <% if servcategory.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(servcategory.errors.count, "error") %> prohibited this servcategory from being saved:</h2>

      <ul>
        <% servcategory.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :category %>
    <%= form.text_field :category %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/servcategories/edit.html.erb
<h1>Editing Servcategory</h1>

<%= render 'form', servcategory: @servcategory %>

<%= link_to 'Show', @servcategory %> |
<%= link_to 'Back', servcategories_path %>

app/views/servcategories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Servcategories</h1>

<table>
  <thead>
    <tr>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @servcategories.each do |servcategory| %>
      <tr>
        <td><%= servcategory.category %></td>
        <td><%= link_to 'Show', servcategory %></td>
        <td><%= link_to 'Edit', edit_servcategory_path(servcategory) %></td>
        <td><%= link_to 'Destroy', servcategory, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Servcategory', new_servcategory_path %>

app/views/servcategories/new.html.erb
<h1>New Servcategory</h1>

<%= render 'form', servcategory: @servcategory %>

<%= link_to 'Back', servcategories_path %>

app/views/servcategories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Category:</strong>
  <%= @servcategory.category %>
</p>

<%= link_to 'Edit', edit_servcategory_path(@servcategory) %> |
<%= link_to 'Back', servcategories_path %>