config/routes.rb
Rails.application.routes.draw do
  resources :invstatuses
  resources :product_orders
  resources :service_orders
  resources :notes
  resources :invoices
  resources :transportations
  resources :chemicals
  resources :suppliers
  resources :supplierpaymentinfos
  resources :supporting_companies
  resources :scpaymentinfos
  resources :stlservices
  resources :servstatuses
  resources :servcategories
  resources :stlclients
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :products
  resources :prodstatuses
  resources :prodcategories
  resources :employees
  resources :home
  devise_for :users

  root to: "home#index"

  get 'home', to: 'home#index'
  get 'report', to: 'reports#show'
  get 'transportation', to: 'transportations#index'
  get 'product', to: 'products#index'
  get 'chemical', to: 'chemicals#index'
  get 'employee', to: 'employees#index'
  get 'stlclient', to: 'stlclients#index'
  get 'supporting', to: 'supporting_companies#index'
  get 'supplier', to: 'suppliers#index'
  get 'invoice', to: 'invoices#index'
  
end

app/models/supplierpaymentinfo.rb
class Supplierpaymentinfo < ApplicationRecord
    belongs_to :supplier
end

app/controllers/supplierpaymentinfos_controller.rb
class SupplierpaymentinfosController < ApplicationController
  before_action :authenticate_user!
  before_action :set_supplierpaymentinfo, only: [:show, :edit, :update, :destroy]

  # GET /supplierpaymentinfos
  # GET /supplierpaymentinfos.json
  def index
    @supplierpaymentinfos = Supplierpaymentinfo.all
  end

  # GET /supplierpaymentinfos/1
  # GET /supplierpaymentinfos/1.json
  def show
  end

  # GET /supplierpaymentinfos/new
  def new
    @supplierpaymentinfo = Supplierpaymentinfo.new
  end

  # GET /supplierpaymentinfos/1/edit
  def edit
  end

  # POST /supplierpaymentinfos
  # POST /supplierpaymentinfos.json
  def create
    @supplierpaymentinfo = Supplierpaymentinfo.new(supplierpaymentinfo_params)

    respond_to do |format|
      if @supplierpaymentinfo.save
        format.html { redirect_to @supplierpaymentinfo, notice: 'Supplierpaymentinfo was successfully created.' }
        format.json { render :show, status: :created, location: @supplierpaymentinfo }
      else
        format.html { render :new }
        format.json { render json: @supplierpaymentinfo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /supplierpaymentinfos/1
  # PATCH/PUT /supplierpaymentinfos/1.json
  def update
    respond_to do |format|
      if @supplierpaymentinfo.update(supplierpaymentinfo_params)
        format.html { redirect_to @supplierpaymentinfo, notice: 'Supplierpaymentinfo was successfully updated.' }
        format.json { render :show, status: :ok, location: @supplierpaymentinfo }
      else
        format.html { render :edit }
        format.json { render json: @supplierpaymentinfo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /supplierpaymentinfos/1
  # DELETE /supplierpaymentinfos/1.json
  def destroy
    @supplierpaymentinfo.destroy
    respond_to do |format|
      format.html { redirect_to supplierpaymentinfos_url, notice: 'Supplierpaymentinfo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_supplierpaymentinfo
      @supplierpaymentinfo = Supplierpaymentinfo.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def supplierpaymentinfo_params
      params.require(:supplierpaymentinfo).permit(:payment_address, :account_name, :account_number, :routing_number, :aba_number, :swift_code, :supplier_id)
    end
end

app/helpers/supplierpaymentinfos_helper.rb
module SupplierpaymentinfosHelper
end

app/views/supplierpaymentinfos/_form.html.erb
<%= form_with(model: supplierpaymentinfo, local: true) do |form| %>
  <% if supplierpaymentinfo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(supplierpaymentinfo.errors.count, "error") %> prohibited this supplierpaymentinfo from being saved:</h2>

      <ul>
        <% supplierpaymentinfo.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :payment_address %>
    <%= form.text_area :payment_address %>
  </div>

  <div class="field">
    <%= form.label :account_name %>
    <%= form.text_field :account_name %>
  </div>

  <div class="field">
    <%= form.label :account_number %>
    <%= form.number_field :account_number %>
  </div>

  <div class="field">
    <%= form.label :routing_number %>
    <%= form.number_field :routing_number %>
  </div>

  <div class="field">
    <%= form.label :aba_number %>
    <%= form.number_field :aba_number %>
  </div>

  <div class="field">
    <%= form.label :swift_code %>
    <%= form.text_field :swift_code %>
  </div>

  <div class="field">
    <%= form.label :supplier_id %>
    <%= form.text_field :supplier_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/supplierpaymentinfos/edit.html.erb
<h1>Editing Supplierpaymentinfo</h1>

<%= render 'form', supplierpaymentinfo: @supplierpaymentinfo %>

<%= link_to 'Show', @supplierpaymentinfo %> |
<%= link_to 'Back', supplierpaymentinfos_path %>

app/views/supplierpaymentinfos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Supplierpaymentinfos</h1>

<table>
  <thead>
    <tr>
      <th>Payment address</th>
      <th>Account name</th>
      <th>Account number</th>
      <th>Routing number</th>
      <th>Aba number</th>
      <th>Swift code</th>
      <th>Supplier</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @supplierpaymentinfos.each do |supplierpaymentinfo| %>
      <tr>
        <td><%= supplierpaymentinfo.payment_address %></td>
        <td><%= supplierpaymentinfo.account_name %></td>
        <td><%= supplierpaymentinfo.account_number %></td>
        <td><%= supplierpaymentinfo.routing_number %></td>
        <td><%= supplierpaymentinfo.aba_number %></td>
        <td><%= supplierpaymentinfo.swift_code %></td>
        <td><%= supplierpaymentinfo.supplier_id %></td>
        <td><%= link_to 'Show', supplierpaymentinfo %></td>
        <td><%= link_to 'Edit', edit_supplierpaymentinfo_path(supplierpaymentinfo) %></td>
        <td><%= link_to 'Destroy', supplierpaymentinfo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Supplierpaymentinfo', new_supplierpaymentinfo_path %>

app/views/supplierpaymentinfos/new.html.erb
<h1>New Supplierpaymentinfo</h1>

<%= render 'form', supplierpaymentinfo: @supplierpaymentinfo %>

<%= link_to 'Back', supplierpaymentinfos_path %>

app/views/supplierpaymentinfos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Payment address:</strong>
  <%= @supplierpaymentinfo.payment_address %>
</p>

<p>
  <strong>Account name:</strong>
  <%= @supplierpaymentinfo.account_name %>
</p>

<p>
  <strong>Account number:</strong>
  <%= @supplierpaymentinfo.account_number %>
</p>

<p>
  <strong>Routing number:</strong>
  <%= @supplierpaymentinfo.routing_number %>
</p>

<p>
  <strong>Aba number:</strong>
  <%= @supplierpaymentinfo.aba_number %>
</p>

<p>
  <strong>Swift code:</strong>
  <%= @supplierpaymentinfo.swift_code %>
</p>

<p>
  <strong>Supplier:</strong>
  <%= @supplierpaymentinfo.supplier_id %>
</p>

<%= link_to 'Edit', edit_supplierpaymentinfo_path(@supplierpaymentinfo) %> |
<%= link_to 'Back', supplierpaymentinfos_path %>